### ISSUE TITLE
Infinite Compost/Bonemeal Bug (Little Composter)

### ISSUE THREAD

**Issue by kylanpl** [Rsl1122/Little-Things#6]
Running in 1.16.1

Plugin works as expected if you rightclick the composter with your desired item.

Many of us use hoppers to automate composting, though. When you do this with compostable items from this plugin, the item in the hopper is never consumed and you effectively get infinite bonemeal.

Here is an example setup
https://i.imgur.com/8oqHVY7.png

**Comment by AuroraLS3** [comment]
Hmm, I wonder if this is a 1.16.1 specific bug 🤔- It was working fine with 1.14 when I made the plugin

**Comment by AuroraLS3** [comment]
Could not reproduce on paper 1.16.5 - may be another plugin interfering or hoppers being disabled

**Comment by AuroraLS3** [comment]
Seems like this was not caught because differences between spigot and paper, where paper would apply changes to the item without setting the item explicitly. I was always running the plugin with Paper
