### ISSUE TITLE
Feature Request: Add option to run command upon getting a banner

### ISSUE THREAD

**Issue by Swirren** [Rsl1122/Little-Things#9]
Would personally use it to send a discordsrv broadcast command

**Comment by AuroraLS3** [comment]
Alright! I guess it needs banners for few new mobs too

**Comment by AuroraLS3** [comment]
Added in 1.1.0.

See example of use here https://github.com/AuroraLS3/Little-Things/blob/master/littlemobbanners/src/main/resources/config.yml#L119

**Comment by Swirren** [comment]
![image](https://user-images.githubusercontent.com/64167426/210525119-3b58b956-7287-482c-ac03-969728031600.png)

Thank you! This looks great.
